### ISSUE TITLE
Couldn't encrypt the message

### ISSUE THREAD

**Issue by hailq** [pubkey/eth-crypto#7]
I followed your tutorial https://github.com/pubkey/eth-crypto/blob/master/tutorials/encrypted-message.md but got this error: 
```
const encrypted = await EthCrypto.encryptWithPublicKey(bob.publicKey,JSON.stringify(payload));
                  ^^^^^

SyntaxError: await is only valid in async function
```

if i remove `await` keyword it would show another error:
```
const encrypted = EthCrypto.encryptWithPublicKey(bob.publicKey,JSON.stringify(payload));
Error: WebCryptoAPI is not available
    at assert (/Users/ho_oh/Developments/hailq/blockchain/my-voting/node_modules/eccrypto/browser.js:15:11)
    at exports.encrypt (/Users/ho_oh/Developments/hailq/blockchain/my-voting/node_modules/eccrypto/browser.js:116:3)
    at Object.encryptWithPublicKey (/Users/ho_oh/Developments/hailq/blockchain/my-voting/node_modules/eth-crypto/dist/lib/encrypt-with-public-key.js:20:34)
```
I used node version 10.6.0

**Comment by hailq** [comment]
And it seems that it doesn't work with nodejs cause there is no WebCryptoAPI module.

**Comment by pubkey** [comment]
It definately works with nodejs. All the unit-tests run against nodejs.

**Comment by hailq** [comment]
nope. i run directly with node on console :?

**Comment by pubkey** [comment]
hmm thats strange.

**Comment by hailq** [comment]
Btw, Is there a tutorial for sending encrypted and decrypted messages by using smart contract ?

**Comment by kyriediculous** [comment]
I can confirm this error on windows.

You need to install OpenSSL-Win64 v1.0.2 (Not 1.1.0)

**Comment by hailq** [comment]
@kyriediculous right, i'm using Mac and i update openssl `brew upgrade openssl`, then reinstall `eccrypto`, and it works now.

**Comment by sowmiyalakshmis** [comment]
I get this same issue... I am using windows 10..i tried updating OpenSSL but still having the same error showing up..what should I do? please help..

**Comment by kyriediculous** [comment]
@sowmiyalakshmis Did you install the version i mentioned above explicitly? 

Also reinstall your libraries, upgrade nodeJS and rebuild the global node modules folder. 

If it doesn't work after that I have no idea I'm afraid.
